achievements/urls.py
from django.conf.urls import url, include
from . import views
from accounts import views as accounts_views
from homepage import views as homepage_views

app_name = 'achievements'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.index, name='to_achievements'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^create_achievement/$', views.create_achievement, name='create_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/delete_achievement/$', views.delete_achievement, name='delete_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/edit_achievement/$', views.edit_achievement, name='edit_achievement'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^ldach$', views.loaddata, name='ldach'),
    url(r'^searched_achievements/$', views.searched_achievements, name='searched_achievements'),
]

publications/urls.py
from django.conf.urls import url, include
from . import views
from accounts import views as accounts_views
from achievements import views as achievements_views
from homepage import views as homepage_views

app_name = 'publications'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^create_publication/$', views.create_publication, name='create_publication'),
    url(r'^(?P<publication_id>[0-99]+)/delete_publication/$', views.delete_publication, name='delete_publication'),
    url(r'^(?P<publication_id>[0-99]+)/edit_publication/$', views.edit_publication, name='edit_publication'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^ld$', views.loaddata, name='ld'),
    url(r'^searched_publications/$', views.searched_publications, name='searched_publications'),
]

ssl2/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as accounts_views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('homepage.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
    url(r'^viewonly/', include('viewonly.urls', namespace="viewonly")),
    url(r'^listall/', accounts_views.listall, name='listall'),
    url(r'^publications/', include('publications.urls', namespace="publications")),
    url(r'^infop/', include('infop.urls', namespace="infop")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

viewonly/urls.py
from django.conf.urls import url ,include
from . import views

app_name = 'viewonly'

urlpatterns = [
	url(r'^(?P<user_name>[a-zA_Z]+)/$', views.index, name='index'),
	url(r'^(?P<user_name>[a-zA-Z]+)/to_homepage$', views.index, name='to_homepage'),
	url(r'^(?P<user_name>[a-zA_Z]+)/to_achievements/$', views.achievements, name='to_achievements'),
	url(r'^(?P<user_name>[a-zA_Z]+)/to_teachings/$', views.teachings, name='to_teachings'),
	url(r'^(?P<user_name>[a-zA_Z]+)/to_publications/$', views.publications, name='to_publications'),
	]

achievements/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Achievements(models.Model):
    user = models.ForeignKey(User, default=1)
    achievement = models.CharField(max_length=250)

    def __str__(self):
        return self.user.username

publications/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Publication(models.Model):
    user = models.ForeignKey(User, default=1)
    publication = models.CharField(max_length=5000)

    def __str__(self):
        return self.user.username

viewonly/models.py
from django.db import models

# Create your models here.

achievements/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Achievements


class AchievementsForm(forms.ModelForm):

    class Meta:
        model = Achievements
        fields = ['achievement']

publications/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Publication


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ['publication']

achievements/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import AchievementsForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .models import Achievements
from infop.models import Info
import requests
from bs4 import BeautifulSoup

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        achnts = Achievements.objects.filter(user=request.user)
        bio = Info.objects.filter(user=request.user)
        return render(request, 'achievements/index.html', {'anshp': bio,'achievements': achnts})

def logoutss(request):
    logout(request)
    return render(request, 'accounts/login.html')

def create_achievement(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        form = AchievementsForm(request.POST or None)
        if form.is_valid():
            achievement = form.save(commit=False)
            achievement.user = request.user                                  
            achievement.save()
            achievements = Achievements.objects.filter(user=request.user)
            return render(request, 'achievements/index.html', {'achievements': achievements})
        context = {
            "form": form,
        }
        return render(request, 'achievements/add_achievement.html', context)

def delete_achievement(request, ach_id):
    tobedeleted = Achievements.objects.get(pk=ach_id)
    tobedeleted.delete()
    achievements = Achievements.objects.filter(user=request.user)
    return render(request, 'achievements/index.html', {'achievements': achievements})


def edit_achievement(request, ach_id):
    tobeedited = Achievements.objects.get(pk=ach_id)
    Achievements.objects.get(pk=ach_id).delete()
    return render(request, 'achievements/add_achievement.html', {'tobeedited': tobeedited , 'error':'aaa'})


def searched_achievements(request):
    achievements = Achievements.objects.filter(user=request.user)
    searched_achievement = request.POST['search1']
    context = {
        'achievements': achievements,
        'searched_achievement': searched_achievement,
    }
    return render(request, 'achievements/searched_achievements.html', context)

def loaddata(request):
    linkobj = Info.objects.filter(user=request.user).first()

    url = linkobj.link

    dic = {}

    res = []

    r  = requests.get(url)

    data = r.text

    # soup = BeautifulSoup(data,'lxml')
    soup = BeautifulSoup(data)

    main = soup.find("div",{ "id" : "fh5co-main" })

    content = soup.find("div",{ "data-content" : "7" })

    ul = content.find("ul")

    publications = ul.find_all("li")

    for item in publications :
        te = item.text

        publ = Achievements.objects.create()

        publ.user = request.user

        publ.achievement = te

        publ.save()

    publiions = Achievements.objects.filter(user=request.user)
    return render(request, 'achievements/index.html', {'achievements': publiions})

publications/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
import json
import urllib
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .forms import PublicationForm
from .models import Publication
from infop.models import Info
from bs4 import BeautifulSoup
import requests


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        publications = Publication.objects.filter(user=request.user)
        bio = Info.objects.filter(user=request.user)
        return render(request, 'publications/index.html', {'anshp': bio,'publications': publications})


def logoutss(request):
    logout(request)
    return render(request, 'accounts/login.html')


def create_publication(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        form = PublicationForm(request.POST or None)
        if form.is_valid():
            publication = form.save(commit=False)
            publication.user = request.user
            publication.save()
            publications = Publication.objects.filter(user=request.user)
            return render(request, 'publications/index.html', {'publications': publications})
        context = {
            "form": form,
        }
        return render(request, 'publications/add_publication.html', context)


def edit_publication(request, publication_id):
    tobeedited = Publication.objects.get(pk=publication_id)
    Publication.objects.get(pk=publication_id).delete()
    return render(request, 'publications/add_publication.html', {'tobeedited': tobeedited , 'error':'aaa'})


def delete_publication(request, publication_id):
    tobedeleted = Publication.objects.get(pk=publication_id)
    tobedeleted.delete()
    publications = Publication.objects.filter(user=request.user)
    return render(request, 'publications/index.html', {'publications': publications})


def searched_publications(request):
    publications = Publication.objects.filter(user=request.user)
    searched_publication = request.POST['search']
    context = {
        'publications': publications,
        'searched_publication': searched_publication,
    }
    return render(request, 'publications/searched_publications.html', context)


def loaddata(request):
    linkobj = Info.objects.filter(user=request.user).first()

    url = linkobj.link

    dic = {}

    res = []

    r = requests.get(url)

    data = r.text

    soup = BeautifulSoup(data,'lxml')

    # soup = BeautifulSoup(data, 'lxml')

    main = soup.findAll("div", {"id": "fh5co-main"})

    content = soup.find("div", {"data-content": "5"})

    # heading = content.find("h4")

    # sp = heading.text.split("\n")

    ul = content.find("ul")

    publications = ul.find_all("li")

    for item in publications :
        te = item.text

        publ = Publication.objects.create()

        publ.user = request.user

        publ.publication = te

        publ.save()

    publiions = Publication.objects.filter(user=request.user)
    return render(request, 'publications/index.html', {'publications': publiions})

viewonly/views.py
from django.shortcuts import render
from homepage.models import Bio
from accounts.models import Teaching
from achievements.models import Achievements
from publications.models import Publication
from django.contrib.auth.models import Permission, User
from infop.models import Info

def index(request,user_name):
	tobeseenuser = User.objects.get(username=user_name)
	bio = Info.objects.filter(user=tobeseenuser)
	context = {
		'anshp': bio,
		'username': user_name
		}
	return render(request, 'viewonly/index.html',context)

def achievements(request,user_name):
	tobeseenuser = User.objects.get(username=user_name)
	achievements = Achievements.objects.filter(user=tobeseenuser)
	bio = Info.objects.filter(user=tobeseenuser)
	context = {
		'anshp': bio,
		'achievements': achievements,
		'username': user_name
		}
	return render(request, 'viewonly/achievements.html',context)

def teachings(request,user_name):
	tobeseenuser = User.objects.get(username=user_name)
	teachings = Teaching.objects.filter(user=tobeseenuser)
	bio = Info.objects.filter(user=tobeseenuser)
	context = {
		'anshp': bio,
		'teachings': teachings,
		'username': user_name
		}	
	return render(request, 'viewonly/teachings.html', context)

def publications(request,user_name):
	tobeseenuser = User.objects.get(username=user_name)
	publications = Publication.objects.filter(user=tobeseenuser)
	bio = Info.objects.filter(user=tobeseenuser)
	context = {
		'anshp': bio,
		'publications': publications,
		'username': user_name
		}	
	return render(request, 'viewonly/publications.html', context)

viewonly/templates/viewonly/achievements.html
{% extends 'a_base2.html' %}

{% block body %}

{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    Hello <br>{{ ansh.0.first_name }}
                </a>
            </div>

            <ul class="nav">
                <li>
                    <a href="{% url 'viewonly:to_homepage' username %}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'viewonly:to_teachings' username %}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'viewonly:to_publications' username %}">
                       <i class="ti-text"></i>
                       Publications
                    </a>
                </li>

                <li class="active">
                    <a href="{% url 'viewonly:to_achievements' username %}">
                        <i class="ti-map"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>

                <li class="active-pro">
                    <a href="{{ anshp.0.link }}">
                        <i class="ti-export"></i>
                        <p>To Personal Homepage</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Achievements</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">5</p>
                                    <p>Notifications</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>

                        <li>
                        <a href="{% url 'accounts:index' %}">
                            Go to your page
                        </a>

                        </li>

                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>

<div class="col-md-9 animated slideInLeft"><h2>Achievements</h2>
</div>

{% if  achievements %}
    <div class="col-lg-12 col-md-10 h-scroll"  >
            {% for ach in achievements %}
                <div class="card animated zoomIn">
                    <div class="content ">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>{{ forloop.counter }}.</label>
                                    <h5>{{ ach.achievement }}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}

            {% endfor %}
    </div>
{% endif %}
{% endblock %}

viewonly/templates/viewonly/index.html
{% extends 'a_base2.html' %}

{% block body %}


<!-- COPY THIS PART TO EVERY PAGE IN THIS APP-->

{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a class="simple-text">
                    Hello <br> {{ anshp.0.first_name }}
                </a>
            </div>

            <ul class="nav">
                
                <li class="active">
                    <a href="{% url 'viewonly:to_homepage' username %}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'viewonly:to_teachings' username %}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'viewonly:to_publications' username %}">
                       <i class="ti-text"></i>
                       Publications
                    </a>
                </li>

                <li>
                    <a href="{% url 'viewonly:to_achievements' username %}">
                        <i class="ti-map"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>

                <li class="active-pro">
                    <a href="{{ anshp.0.link }}">
                        <i class="ti-export"></i>
                        <p>To Personal Homepage</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Homepage</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">5</p>
                                    <p>Notifications</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>

                        <li>
                        <a href="{% url 'accounts:index' %}">
                            Go to your page
                        </a>

                        </li>

                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>

 <div class="content">
            <div class="container-fluid">
                
                        <div class="wrapper">
                            <div class="profile-background">
                                <div class="filter-black"></div>
                            </div>
                        {% for ansh in anshp %}
                        <div class="card card-user">
                            <div class="image">
                                 <img src="http://www.iitg.ernet.in/html/images/logo.png" height="100px"  alt="..."/>
                            </div>
                            <div class="content">
                                <div class="author">
                                   
                                 {% if ansh.p_photo %} <img class="avatar border-white" src="{{ ansh.p_photo.url }}" alt="..."/>
                                 {% else %} <img class="avatar border-white" src="{% static 'accounts/img/faces/face-1.jpg'%}" alt="..."/>
                                 {% endif %}
                                  <h4>{{ ansh.first_name }} {{ ansh.last_name }}</h4>
                                  <h5 class="title">{{ ansh.username }}<br />
                                     <a href="#"><small>{{ ansh.email }}</small></a>
                                  </h5>
                                </div>
                                <p class="description text-center">
                                    <strong>{{ ansh.dept }}</strong><br>
                                    {{ ansh.about }} <br>

                                </p>
                            </div>
                            <hr>
                            <div class="text-center">
                                <div class="row">
                                    <div class="col-md-4 col-md-offset-1">
                                        <h5>{{ ansh.phone_number }}<br /><small>Contact</small></h5>
                                    </div>
                                    <div class="col-md-3">
                                        <h5>{{ ansh.designation }}<br /><small>Authority</small></h5>
                                    </div>
                                    <div class="col-md-3">
                                        <h5>{{ ansh.institute_name }}<br /><small>At</small></h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        </div>
                    </div>
                </div>

                
                    


{% endblock %}

viewonly/templates/viewonly/publications.html
{% extends 'a_base2.html' %}

{% block body %}

{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                   Hello <br>{{ ansh.0.first_name }}
                </a>
            </div>

            <ul class="nav">
                
                <li>
                    <a href="{% url 'viewonly:to_homepage' username %}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'viewonly:to_teachings' username %}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'viewonly:to_publications' username %}">
                       <i class="ti-text"></i>
                       Publications
                    </a>
                </li>

                <li>
                    <a href="{% url 'viewonly:to_achievements' username %}">
                        <i class="ti-map"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>

               <li class="active-pro">
                    <a href="{{ anshp.0.link }}">
                        <i class="ti-export"></i>
                        <p>To Personal Homepage</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Publications</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        
                        <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-bell"></i>
                                    <p class="notification">5</p>
                                    <p>Notifications</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="#">Notification 1</a></li>
                                <li><a href="#">Notification 2</a></li>
                                <li><a href="#">Notification 3</a></li>
                                <li><a href="#">Notification 4</a></li>
                                <li><a href="#">Another notification</a></li>
                              </ul>
                        </li>

                        <li>
                        <a href="{% url 'accounts:index' %}">
                            Go to your page
                        </a>

                        </li>

                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    
                    </ul>

                </div>
            </div>
        </nav>

<div class="col-md-9 animated slideInLeft"><h2>Publications</h2>
</div>
{#<style>#}
{#  p {#}
{#    width: 100px;#}
{#    padding: 10px;#}
{#    background-color: #ccc;#}
{#}#}
{#    p.letters {#}
{#    word-wrap: break-word;#}
{#}#}
{#</style>#}

{% if  publications %}
    <div class="col-lg-12 col-md-10 h-scroll"  >
            {% for ach in publications %}
                <div class="card animated zoomIn">
                    <div class="content animated ">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>{{ forloop.counter }}.</label>
                                     <h5>{{ ach.publication }}</h5>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
    </div>
{% endif %}

{% endblock %}