accounts/urls.py
from django.conf.urls import url, include
from . import views
from homepage import views as homepage_views
from django.contrib.auth.views import password_reset , password_reset_done, password_reset_confirm

app_name = 'accounts'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^create_teaching/$', views.create_teaching, name='create_teaching'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^admin/$', views.dummy, name='admin'),
    # url(r'^verified-email-field/', include('verified_email_field.urls')),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #     name='activate'),
    url(r'^(?P<teaching_id>[0-99]+)/delete_teaching/$', views.delete_teaching, name='delete_teaching'),
    url(r'^addimage/$', views.addimage, name='addimage'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^(?P<teaching_id>[0-99]+)/set_previous/$', views.set_previous, name='set_previous'),
    url(r'^searched_user/$', views.searched_user, name='searched_user'),
    url(r'^listall/$', views.listall, name='listall'),
    url(r'^send/$', views.send, name='send'),
	url(r'^messaging/$', views.messaging, name='messaging'),
    url(r'^message/$', views.message, name='message'),
    url(r'^(?P<message_id>[0-99]+)/delete_messages/$', views.delete_messages, name='delete_messages'),
    url(r'^ldtea$', views.loaddata, name='ldtea'),
    # url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^reset_password/$', password_reset, name='reset_password'),
    url(r'^reset_password_done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^login/$', views.login_user, name='login_user'),
]

achievements/urls.py
from django.conf.urls import url, include
from . import views
from accounts import views as accounts_views
from homepage import views as homepage_views

app_name = 'achievements'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.index, name='to_achievements'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^create_achievement/$', views.create_achievement, name='create_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/delete_achievement/$', views.delete_achievement, name='delete_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/edit_achievement/$', views.edit_achievement, name='edit_achievement'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^ldach$', views.loaddata, name='ldach'),
    url(r'^searched_achievements/$', views.searched_achievements, name='searched_achievements'),
]

homepage/urls.py
from django.conf.urls import url ,include
from . import views
from accounts import views as accounts_views
from achievements import views as achievements_views
from publications import views as publications_views

app_name = 'homepage'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^logout/$', views.logoutss, name='logout'),
	url(r'^create_bio/$', views.create_bio, name='create_bio'),
	url(r'^create_office_details/$', views.create_office_details, name='create_office_details'),
	url(r'^create_research_interests/$', views.create_research_interests, name='create_research_interests'),
	url(r'^create_work_experience/$', views.create_work_experience, name='create_work_experience'),
	url(r'^(?P<bio_id>[0-99]+)/delete_bio/$', views.delete_bio, name='delete_bio'),
	url(r'^to_teaching/$', accounts_views.index, name='to_teaching'),
	url(r'^to_achievements/$', achievements_views.index, name='to_achievements'),
	url(r'^to_publications/$', publications_views.index, name='to_publications'),
	url(r'^(?P<office_id>[0-99]+)/delete_office/$', views.delete_office, name='delete_office'),
	url(r'^(?P<office_id>[0-99]+)/delete_office/$', views.delete_office, name='delete_teaching'),
	url(r'^(?P<work_id>[0-99]+)/delete_work/$', views.delete_work, name='delete_work'),
	url(r'^(?P<research_id>[0-99]+)/delete_research/$', views.delete_research, name='delete_research'),
	]



	

infop/urls.py
from django.conf.urls import url
from . import views
from homepage import views as homepage_views
from accounts import views as accounts_views

app_name = 'infop'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^save/$', views.save, name='save'),
    url(r'^to_teaching/$', accounts_views.index, name='to_teaching'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
]

publications/urls.py
from django.conf.urls import url, include
from . import views
from accounts import views as accounts_views
from achievements import views as achievements_views
from homepage import views as homepage_views

app_name = 'publications'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^create_publication/$', views.create_publication, name='create_publication'),
    url(r'^(?P<publication_id>[0-99]+)/delete_publication/$', views.delete_publication, name='delete_publication'),
    url(r'^(?P<publication_id>[0-99]+)/edit_publication/$', views.edit_publication, name='edit_publication'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^ld$', views.loaddata, name='ld'),
    url(r'^searched_publications/$', views.searched_publications, name='searched_publications'),
]

ssl2/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as accounts_views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('homepage.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
    url(r'^viewonly/', include('viewonly.urls', namespace="viewonly")),
    url(r'^listall/', accounts_views.listall, name='listall'),
    url(r'^publications/', include('publications.urls', namespace="publications")),
    url(r'^infop/', include('infop.urls', namespace="infop")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

publications/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Publication(models.Model):
    user = models.ForeignKey(User, default=1)
    publication = models.CharField(max_length=5000)

    def __str__(self):
        return self.user.username

publications/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Publication


class PublicationForm(forms.ModelForm):

    class Meta:
        model = Publication
        fields = ['publication']

publications/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
import json
import urllib
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .forms import PublicationForm
from .models import Publication
from infop.models import Info
from bs4 import BeautifulSoup
import requests


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        publications = Publication.objects.filter(user=request.user)
        bio = Info.objects.filter(user=request.user)
        return render(request, 'publications/index.html', {'anshp': bio,'publications': publications})


def logoutss(request):
    logout(request)
    return render(request, 'accounts/login.html')


def create_publication(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        form = PublicationForm(request.POST or None)
        if form.is_valid():
            publication = form.save(commit=False)
            publication.user = request.user
            publication.save()
            publications = Publication.objects.filter(user=request.user)
            return render(request, 'publications/index.html', {'publications': publications})
        context = {
            "form": form,
        }
        return render(request, 'publications/add_publication.html', context)


def edit_publication(request, publication_id):
    tobeedited = Publication.objects.get(pk=publication_id)
    Publication.objects.get(pk=publication_id).delete()
    return render(request, 'publications/add_publication.html', {'tobeedited': tobeedited , 'error':'aaa'})


def delete_publication(request, publication_id):
    tobedeleted = Publication.objects.get(pk=publication_id)
    tobedeleted.delete()
    publications = Publication.objects.filter(user=request.user)
    return render(request, 'publications/index.html', {'publications': publications})


def searched_publications(request):
    publications = Publication.objects.filter(user=request.user)
    searched_publication = request.POST['search']
    context = {
        'publications': publications,
        'searched_publication': searched_publication,
    }
    return render(request, 'publications/searched_publications.html', context)


def loaddata(request):
    linkobj = Info.objects.filter(user=request.user).first()

    url = linkobj.link

    dic = {}

    res = []

    r = requests.get(url)

    data = r.text

    soup = BeautifulSoup(data,'lxml')

    # soup = BeautifulSoup(data, 'lxml')

    main = soup.findAll("div", {"id": "fh5co-main"})

    content = soup.find("div", {"data-content": "5"})

    # heading = content.find("h4")

    # sp = heading.text.split("\n")

    ul = content.find("ul")

    publications = ul.find_all("li")

    for item in publications :
        te = item.text

        publ = Publication.objects.create()

        publ.user = request.user

        publ.publication = te

        publ.save()

    publiions = Publication.objects.filter(user=request.user)
    return render(request, 'publications/index.html', {'publications': publiions})

publications/templates/publications/data.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
{{ detail }}
</body>
</html>

publications/templates/publications/index.html
{% extends 'a_base2.html' %}

{% block body %}

{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                     Welcome<br>
                    {{ request.user.username }}
                </a>
            </div>

            <ul class="nav">

                <li>
                    <a href="{% url 'infop:index'%}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'infop:to_teaching'%}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'publications:index'%}">
                        <i class="ti-text"></i>
                        <p>Publications</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:to_achievements' %}">
                        <i class="ti-cup"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                   <a href="{% url 'accounts:messaging' %}">
                        <i class="ti-comments"></i>

                        {% if not request.user.last_name == request.user.first_name%}
                            <div style="color:red; font-weight: bold">{{ request.user.last_name}} new </div>
                        {% endif %}
                       <p>MESSEGES</p>


                    </a>
                </li>
                <li class="active-pro">
                    <a href="http://intranet.iitg.ernet.in/">
                        <i class="ti-export"></i>
                        <p>Intranet</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Publications</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>

                            <form action="{% url 'publications:searched_publications' %}" method = "POST">
                                {% csrf_token %}
                                <input type="text" name="search"  placeholder="  Search Publications" size="40">
                                <button type="submit" class="btn btn-success">Search</button>
                            </form>
                        </li>

                         <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-settings"></i>
                                    <p>Settings</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:reset_password' %}">Change Password</a></li>

                              </ul>
                        </li>
                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>


<div class="col-md-9 animated slideInLeft"><h2>My Publications</h2>
</div>

    <div class="col-md-1 animated slideInRight"  style="padding-top: 25px">
        <a href="{% url 'publications:ld' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-circle-arrow-down"> Load</span>
            </button>
        </a>
    </div>


    <div class="col-md-1 animated slideInRight"  style="padding-top: 25px">
        <a href="{% url 'publications:create_publication' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus">Add Publication</span>
            </button>
        </a>
    </div>
{#<style>#}
{#  p {#}
{#    width: 100px;#}
{#    padding: 10px;#}
{#    background-color: #ccc;#}
{#}#}
{#    p.letters {#}
{#    word-wrap: break-word;#}
{#}#}
{#</style>#}

{% if  publications %}
    <div class="col-lg-12 col-md-10 h-scroll"  >
            {% for ach in publications %}
                <div class="card animated zoomIn">
                    <div class="content animated ">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>{{ forloop.counter }}.</label>
                                     <h5>{{ ach.publication }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1">
                                <div class="form-group">
                                    <form action="{% url 'publications:edit_publication'  ach.id %}" method="POST" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="ach_id" value="{{ ach.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <div class="form-group">
                                    <form action="{% url 'publications:delete_publication'  ach.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="ach_id" value="{{ ach.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
    </div>
{% endif %}


    </div>
</div>
{% endblock %}

publications/templates/publications/searched_publications.html
{% extends 'a_base2.html' %}

{% block body %}


{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                    Welcome<br>
                    {{ request.user.username }}
                </a>
            </div>

            <ul class="nav">

                <li>
                    <a href="{% url 'infop:index'%}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'infop:to_teaching'%}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'publications:index'%}">
                        <i class="ti-text"></i>
                        <p>Publications</p>
                    </a>
                </li>
                <li >
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:to_achievements' %}">
                        <i class="ti-cup"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                   <a href="{% url 'accounts:messaging' %}">
                        <i class="ti-comments"></i>

                        {% if not request.user.last_name == request.user.first_name%}
                            <div style="color:red; font-weight: bold">{{ request.user.last_name}} new </div>
                        {% endif %}
                       <p>MESSEGES</p>


                    </a>
                </li>
                <li class="active-pro">
                    <a href="http://intranet.iitg.ernet.in/">
                        <i class="ti-export"></i>
                        <p>Intranet</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Publications</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <form action="{% url 'publications:searched_publications'%}" method = "POST">
                                {% csrf_token %}
                                <input type="text" name="search"  placeholder="  Search Publications" size="40">
                                <button type="submit" class="btn btn-success">Search</button>
                            </form>
                        </li>
                        <li>
                            <form action="{% url 'publications:index'%}" method = "POST">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-success">Back</button>
                            </form>
                        </li>


                         <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-settings"></i>
                                    <p>Settings</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:reset_password' %}">Change Password</a></li>

                              </ul>
                        </li>

                        <li>
	                        <a href="{% url 'accounts:index' %}">
	                            Go to your page
	                        </a>

                        </li>
                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>


{#	<ul>#}
{##}
{##}
{##}
{#        {% for ach in publications%}#}
{#			{% if searched_publication.lower in ach.publication.lower %}#}
{#                <li>#}
{#               {{ ach.publication }}#}
{#                </li>#}
{#            {% endif %}#}
{##}
{#		{% endfor %}#}
{#	</ul>#}

    <div class="col-md-9 animated slideInLeft"><h2>Searched Results</h2>
</div>

    <div class="col-md-1 animated slideInRight"  style="padding-top: 25px">
        <a href="{% url 'publications:ld' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-circle-arrow-down"> Load</span>
            </button>
        </a>
    </div>


    <div class="col-md-1 animated slideInRight"  style="padding-top: 25px">
        <a href="{% url 'publications:create_publication' %}">
            <button type="button" class="btn btn-success">
                <span class="glyphicon glyphicon-plus">Add Publication</span>
            </button>
        </a>
    </div>


{#<h2>Enter achievement data</h2>#}

{% if  publications %}
    <div class="col-lg-12 col-md-10 h-scroll"  >
            {% for ach in publications %}
                {% if searched_publication.lower in ach.publication.lower %}
                <div class="card animated zoomIn">
                    <div class="content ">
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="form-group">
                                    <label>{{ forloop.counter }}.</label>
                                     <h5>{{ ach.publication }}</h5>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-1">
                                <div class="form-group">
                                    <form action="{% url 'publications:delete_publication'  ach.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="ach_id" value="{{ ach.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                            <div class="col-md-1">
                                <div class="form-group">
                                    <form action="{% url 'publications:delete_publication'  ach.id %}" method="post" style="display: inline;">
                                        {% csrf_token %}
                                        <input type="hidden" name="ach_id" value="{{ ach.id }}" />
                                        <button type="submit" class="btn btn-default btn-sm">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endif  %}
            {% endfor %}
    </div>
{% endif %}

    </div>
</div>
{% endblock %}