accounts/urls.py
from django.conf.urls import url, include
from . import views
from homepage import views as homepage_views
from django.contrib.auth.views import password_reset , password_reset_done, password_reset_confirm

app_name = 'accounts'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^create_teaching/$', views.create_teaching, name='create_teaching'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^admin/$', views.dummy, name='admin'),
    # url(r'^verified-email-field/', include('verified_email_field.urls')),
    # url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', views.activate,
    #     name='activate'),
    url(r'^(?P<teaching_id>[0-99]+)/delete_teaching/$', views.delete_teaching, name='delete_teaching'),
    url(r'^addimage/$', views.addimage, name='addimage'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^(?P<teaching_id>[0-99]+)/set_previous/$', views.set_previous, name='set_previous'),
    url(r'^searched_user/$', views.searched_user, name='searched_user'),
    url(r'^listall/$', views.listall, name='listall'),
    url(r'^send/$', views.send, name='send'),
	url(r'^messaging/$', views.messaging, name='messaging'),
    url(r'^message/$', views.message, name='message'),
    url(r'^(?P<message_id>[0-99]+)/delete_messages/$', views.delete_messages, name='delete_messages'),
    url(r'^ldtea$', views.loaddata, name='ldtea'),
    # url(r'^change_password/$', views.change_password, name='change_password'),
    url(r'^reset_password/$', password_reset, name='reset_password'),
    url(r'^reset_password_done/$', password_reset_done, name='password_reset_done'),
    url(r'^reset_password_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm, name='password_reset_confirm'),
    url(r'^login/$', views.login_user, name='login_user'),
]

homepage/urls.py
from django.conf.urls import url ,include
from . import views
from accounts import views as accounts_views
from achievements import views as achievements_views
from publications import views as publications_views

app_name = 'homepage'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(r'^logout/$', views.logoutss, name='logout'),
	url(r'^create_bio/$', views.create_bio, name='create_bio'),
	url(r'^create_office_details/$', views.create_office_details, name='create_office_details'),
	url(r'^create_research_interests/$', views.create_research_interests, name='create_research_interests'),
	url(r'^create_work_experience/$', views.create_work_experience, name='create_work_experience'),
	url(r'^(?P<bio_id>[0-99]+)/delete_bio/$', views.delete_bio, name='delete_bio'),
	url(r'^to_teaching/$', accounts_views.index, name='to_teaching'),
	url(r'^to_achievements/$', achievements_views.index, name='to_achievements'),
	url(r'^to_publications/$', publications_views.index, name='to_publications'),
	url(r'^(?P<office_id>[0-99]+)/delete_office/$', views.delete_office, name='delete_office'),
	url(r'^(?P<office_id>[0-99]+)/delete_office/$', views.delete_office, name='delete_teaching'),
	url(r'^(?P<work_id>[0-99]+)/delete_work/$', views.delete_work, name='delete_work'),
	url(r'^(?P<research_id>[0-99]+)/delete_research/$', views.delete_research, name='delete_research'),
	]



	

infop/urls.py
from django.conf.urls import url
from . import views
from homepage import views as homepage_views
from accounts import views as accounts_views

app_name = 'infop'

urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^save/$', views.save, name='save'),
    url(r'^to_teaching/$', accounts_views.index, name='to_teaching'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
]

ssl2/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as accounts_views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('homepage.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
    url(r'^viewonly/', include('viewonly.urls', namespace="viewonly")),
    url(r'^listall/', accounts_views.listall, name='listall'),
    url(r'^publications/', include('publications.urls', namespace="publications")),
    url(r'^infop/', include('infop.urls', namespace="infop")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
import datetime


# Create your models here.

class Teaching(models.Model):
    user = models.ForeignKey(User, default=1)
    coursename = models.CharField(max_length=250)
    start_month = models.CharField(max_length=100)
    start_year = models.CharField(max_length=100)
    is_ongoing = models.BooleanField(default=True)
    teacher_name = models.CharField(max_length=100)

    def __str__(self):
        return self.coursename + ' - ' + self.start_year


class Image(models.Model):
    user = models.ForeignKey(User, default=1)
    profile_photo = models.FileField()


class Mailing(models.Model):
    teacher = models.CharField(max_length=100, default=1)
    sender = models.CharField(max_length=100, default="ADMIN")
    inbox = models.CharField(max_length=10000, default="Welcome to Our website")
    date = models.DateTimeField(default=datetime.datetime.now(), blank=True)

    def __str__(self):
        return self.teacher

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Teaching,Image


class AddTeachingForm(forms.ModelForm):

    class Meta:
        model = Teaching
        fields = ['coursename', 'start_month', 'start_year', 'teacher_name','is_ongoing']

class UserForm(forms.ModelForm):
    email = forms.EmailField(max_length=200, help_text='Required')
    password = forms.CharField(widget=forms.PasswordInput)
    password1 = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password' , 'password1']

class AddProfilePhoto(forms.ModelForm):

		class Meta:
			model = Image
			fields = ['profile_photo']
# class SongForm(forms.ModelForm):

#     class Meta:
#         model = Song
#         fields = ['song_title', 'audio_file']


# class UserForm(forms.ModelForm):
#     password = forms.CharField(widget=forms.PasswordInput)

#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password']

accounts/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import AddTeachingForm,UserForm,AddProfilePhoto
import json
import urllib
from django.conf import settings
from .models import Teaching,Image,Mailing
from django.http import HttpResponse
from django.shortcuts import render, redirect
# from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from homepage.models import Bio
from infop.models import Info
import datetime
import requests
from bs4 import BeautifulSoup

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        teachings = Teaching.objects.filter(user=request.user)
        bio = Info.objects.filter(user=request.user)
        query = request.GET.get("q")
        if query:
            teachings = teachings.filter(
                Q(coursename__icontains=query) |
                Q(startyear__icontains=query)
            ).distinct()
            return render(request, 'accounts/index.html', {
                'anshp': bio,
                'teachings': teachings,
            })
        else:
            return render(request, 'accounts/index.html', {'anshp': bio,'teachings': teachings})

def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                ansh=Info.objects.filter(user=request.user)
                return render(request, 'infop/index.html', {'anshp': ansh})
            else:
                return render(request, 'accounts/login.html', {'error_message': 'Your account has been disabled'})
        else:
            return render(request, 'accounts/login.html', {'error_message': 'Invalid login'})
    return render(request, 'accounts/login.html')


def create_teaching(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        form = AddTeachingForm(request.POST or None)
        if form.is_valid():
            teaching = form.save(commit=False)
            teaching.user = request.user                                  

            teaching.save()
            teaings = Teaching.objects.filter(user=request.user)
            return render(request, 'accounts/index.html', {'teachings': teaings})
            # change index.html here to details.html
        
        context = {
            "form": form,
        }
        
        return render(request, 'accounts/add_teaching.html', context)


# def register(request):
#     if request.method == "POST":
#
#         form = UserForm(request.POST or None)
#         if form.is_valid():
#             user = form.save(commit=False)
#             username = form.cleaned_data['username']
#             email = form.cleaned_data['email']
#             password = form.cleaned_data['password']
#             password1 = form.cleaned_data['password1']
#
#             ''' Begin reCAPTCHA validation '''
#             recaptcha_response = request.POST.get('g-recaptcha-response')
#             url = 'https://www.google.com/recaptcha/api/siteverify'
#             values = {
#                 'secret': "6LdOmjcUAAAAAF1dXs-eIVwrygU-Ii7Eyo7pcggk",
#                 'response': recaptcha_response
#             }
#             data = urllib.parse.urlencode(values).encode()
#             req = urllib.request.Request(url, data=data)
#             response = urllib.request.urlopen(req)
#             result = json.loads(response.read().decode())
#             ''' End reCAPTCHA validation '''
#
#             if password == password1 and result['success']:
#                 object = Mailing.objects.create(teacher=username, date=datetime.datetime.now())
#                 objecct1 = Info.objects.create(username=username)
#                 user.set_password(password)
#                 user.last_name = "0"
#                 user.first_name = "0"
#                 user.is_active = False
#                 user.save()
#                 current_site = get_current_site(request)
#                 message = render_to_string('accounts/acc_active_email.html', {
#                     'user': user,
#                     'domain': current_site.domain,
#                     'uid': urlsafe_base64_encode(force_bytes(user.pk)),
#                     'token': account_activation_token.make_token(user),
#                 })
#                 mail_subject = 'Activate your account.'
#                 to_email = form.cleaned_data.get('email')
#                 email = EmailMessage(mail_subject, message, to=[to_email])
#                 email.send()
#                 return HttpResponse('Please confirm your email address to complete the registration')
#                     # user = authenticate(username=username, password=password)
#                     # if user is not None:
#                     #     if user.is_active:
#                     #         login(request, user)
#                     #         teachings = Teaching.objects.filter(user=request.user)
#                     #         return render(request, 'accounts/index.html', {'teachings': teachings})
#             elif password != password1:
#                 return render(request, 'accounts/login.html', {'error_message': 'Password dont match '})
#         return render(request, 'accounts/login.html', {'error_message': 'Invalid Email or No Captcha'})


def register(request):
    if request.method == "POST":

        form = UserForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            password1 = form.cleaned_data['password1']


            if password == password1:
                user.set_password(password)
                user.last_name = "0"
                user.first_name = "0"
                user.is_active = True
                user.save()
                login(request, user)
                object = Mailing.objects.create(teacher=username, date=datetime.datetime.now())
                object1 = Info.objects.create()
                object1.user = request.user
                object1.username = username
                object1.save()
                anshp = Info.objects.filter(username=request.user.username)
                return render(request, 'infop/index.html', {'anshp': anshp})

            elif password != password1:
                return render(request, 'accounts/login.html', {'error_message': 'Password dont match '})
        return render(request, 'accounts/login.html', {'error_message': 'Invalid Email or No Captcha'})


def logoutss(request):
    logout(request)
    return render(request, 'accounts/login.html')

def dummy(request):
    return

# def activate(request, uidb64, token):
#     try:
#         uid = force_text(urlsafe_base64_decode(uidb64))
#         user = User.objects.get(pk=uid)
#     except(TypeError, ValueError, OverflowError, User.DoesNotExist):
#         user = None
#     if user is not None and account_activation_token.check_token(user, token):
#         user.is_active = True
#
#         user.save()
#
#         login(request, user)
#         object = Info.objects.create(user=request.user)
#         # return redirect('home')
#         teachings = Teaching.objects.filter(user=request.user)
#         anshp= Info.objects.filter(user=request.user)
#         return render(request, 'infop/index.html', {'anshp': anshp})
#     else:
#         return HttpResponse('Activation link is invalid!')

def delete_teaching(request, teaching_id):
    tobedeleted = Teaching.objects.get(pk=teaching_id)
    tobedeleted.delete()
    teachings = Teaching.objects.filter(user=request.user)
    return render(request, 'accounts/index.html', {'teachings': teachings})

def addimage(request):
    teachings = Teaching.objects.filter(user=request.user)
    if not request.user.is_authenticated():
        return render(request, 'music/login.html')
    else:
        form = AddProfilePhoto(request.POST or None, request.FILES or None)
        if form.is_valid():
            photo = form.save(commit=false)
            photo.user = request.user
            photo.profile_photo = request.FILES['profile_photo']
            photo.save()
            context = {
            'form':form,
            'teachings': teachings,
            'image': photo,
            }
            return render(request, 'accounts/index.html',context)
    return render(request, 'accounts/index.html',{'teachings': teachings})

def listall(request):
    users = User.objects.all()
    profiles = Info.objects.all()
    context = {
        'users': users,
        'profiles': profiles,
    }
    return render(request, 'accounts/listall.html',context)

def searched_user(request):
    users = User.objects.all()
    searched_user = request.POST['user_name']
    context = {
        'users': users,
        'searched_user': searched_user,
    }
    return render(request, 'accounts/searched_user.html',context)

def set_previous(request, teaching_id):
    tobeedited = Teaching.objects.get(pk=teaching_id)
    tobedeleted = Teaching.objects.get(pk=teaching_id)
    tobedeleted.delete()
    tobeedited.is_ongoing=False
    tobeedited.save()
    teachings = Teaching.objects.filter(user=request.user)
    return render(request, 'accounts/index.html', {'teachings': teachings})

accounts/templates/accounts/index.html
{% extends 'a_base2.html' %}

{% block body %}

{% load staticfiles %}

<div class="wrapper">
    <div class="sidebar" data-background-color="black" data-active-color="warning">

    <!--
        Tip 1: you can change the color of the sidebar's background using: data-background-color="white | black"
        Tip 2: you can change the color of the active button using the data-active-color="primary | info | success | warning | danger"
    -->

        <div class="sidebar-wrapper">
            <div class="logo">
                <a href="#" class="simple-text">
                     Welcome<br>
                    {{ anshp.0.first_name }}
                </a>
            </div>

            <ul class="nav">

                <li>
                    <a href="{% url 'infop:index'%}">
                        <i class="ti-user"></i>
                        <p>User Profile</p>
                    </a>
                </li>
                <li class="active">
                    <a href="{% url 'infop:to_teaching'%}">
                        <i class="ti-panel"></i>
                        <p>Teachings</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'publications:index'%}">
                        <i class="ti-text"></i>
                        <p>Publications</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'listall' %}">
                        <i class="ti-pencil-alt2"></i>
                        <p>All Pages</p>
                    </a>
                </li>
                <li>
                    <a href="{% url 'homepage:to_achievements' %}">
                        <i class="ti-cup"></i>
                        <p>Achievements</p>
                    </a>
                </li>
                <li>
                   <a href="{% url 'accounts:messaging' %}">
                        <i class="ti-comments"></i>

                        {% if not request.user.last_name == request.user.first_name%}
                            <div style="color:red; font-weight: bold">{{ request.user.last_name}} new </div>
                        {% endif %}
                       <p>MESSEGES</p>


                    </a>
                </li>
                <li class="active-pro">
                    <a href="{{ anshp.0.link }}">
                        <i class="ti-export"></i>
                        <p>To Personal Homepage</p>
                    </a>
                </li>
            </ul>
        </div>
    </div>

    <div class="main-panel">
        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar bar1"></span>
                        <span class="icon-bar bar2"></span>
                        <span class="icon-bar bar3"></span>
                    </button>
                    <a class="navbar-brand" href="#">Teachings</a>
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav navbar-right">
                       <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                    <i class="ti-settings"></i>
                                    <p>Settings</p>
                                    <b class="caret"></b>
                              </a>
                              <ul class="dropdown-menu">
                                <li><a href="{% url 'accounts:reset_password' %}">Change Password</a></li>
                              </ul>
                        </li>
                        <li>
                        <a href="{% url 'accounts:logout' %}">
                            <span class="glyphicon glyphicon-off" aria-hidden="true"></span> Logout
                        </a>

                        </li>
                    </ul>

                </div>
            </div>
        </nav>

        <div class="row">
            <div class="col-md-6 animated slideInLeft" ><h2>Ongoing</h2></div>
            <div class="col-md-3 animated slideInRight" ><h2>Previous</h2></div>
            <div class="col-md-1 animated slideInRight"  style="padding-top: 25px">
                <a href="{% url 'accounts:ldtea' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-circle-arrow-down"> Load</span>
                    </button>
                </a>
            </div>


            <div class="col-md-2 animated slideInRight"  style="padding-top: 25px">
                <a href="{% url 'accounts:create_teaching' %}">
                    <button type="button" class="btn btn-success">
                        <span class="glyphicon glyphicon-plus">Add Teaching</span>
                    </button>
                </a>
            </div>
        </div>

        <div class="content">
            <div class="container-fluid ">
                <div class="row">
                    <div class="col-lg-6 col-md-6 h-scroll">
                        {% if  teachings %}
                        {% for teaching in teachings %}
                        {% if teaching.is_ongoing %}
                         <div class="card animated slideInLeft">

                             <div class="content">
                                 <h4><b>{{ teaching.coursename }}</b></h4>
                                <h6>{{ teaching.start_month }}</h6>
                                <h6>{{ teaching.start_year }}</h6>
                                <br>

                                 <form action="{% url 'accounts:delete_teaching' teaching.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                                <form action="{% url 'accounts:set_previous' teaching.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-ok"></span>
                                    </button>
                                </form>
                             </div>

                         </div>
                        {% endif %}
                        {% endfor %}
                        {% endif %}

                    </div>
                    <div class="col-lg-6 col-md-6 h-scroll">
                            {% if  teachings %}
                            {% for teaching in teachings %}
                            {% if not teaching.is_ongoing %}
                         <div class="card animated slideInRight">
                            <div class="content">
                                <h4><b>{{ teaching.coursename }}</b></h4>
                                <h6>{{ teaching.start_month }}</h6>
                                <h6>{{ teaching.start_year }}</h6>
                                <br>

                                 <form action="{% url 'accounts:delete_teaching' teaching.id %}" method="post" style="display: inline;">
                                    {% csrf_token %}
                                    <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />
                                    <button type="submit" class="btn btn-default btn-sm">
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </button>
                                </form>

                            </div>
                         </div>
                        {% endif %}
                    {% endfor %}
                    {% endif %}
                    </div>
                </div>
            </div>
        </div>

{#        <ul class="list-unstyled follows">#}
{##}
{##}
{#        {% if  teachings %}#}
{#            {% for teaching in teachings %}#}
{#                {% if teaching.is_ongoing %}#}
{#                    <li>#}
{#                        <div class="col-sm-4 col-lg-2">#}
{#                                    <div class="thumbnail">#}
{#                                        <div class="caption">#}
{#                            <h3><b>{{ teaching.coursename }}</b></h3>#}
{#                            <h5>{{ teaching.start_month }}</h5>#}
{#                            <h5>{{ teaching.start_year }}</h5>#}
{#                            <br>#}
{#                            <!-- Delete Teaching -->#}
{#                            <form action="{% url 'accounts:delete_teaching' teaching.id %}" method="post" style="display: inline;">#}
{#                                {% csrf_token %}#}
{#                                <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />#}
{#                                <button type="submit" class="btn btn-default btn-sm">#}
{#                                    <span class="glyphicon glyphicon-trash"></span>#}
{#                                </button>#}
{#                            </form>#}
{##}
{#                            <form action="{% url 'accounts:set_previous' teaching.id %}" method="post" style="display: inline;">#}
{#                                {% csrf_token %}#}
{#                                <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />#}
{#                                <button type="submit" class="btn btn-default btn-sm">#}
{#                                    <span class="glyphicon glyphicon-ok"></span>#}
{#                                </button>#}
{#                            </form>#}
{##}
{##}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </li>#}
{#                {% endif %}#}
{#        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#        <h2>Previous</h2>#}
{#        {% if  teachings %}#}
{#            {% for teaching in teachings %}#}
{#                {% if not teaching.is_ongoing %}#}
{#                    <li>#}
{#                        <div class="col-sm-4 col-lg-2">#}
{#                                    <div class="thumbnail">#}
{#                                        <div class="caption">#}
{#                            <h3><b>{{ teaching.coursename }}</b></h3>#}
{#                            <h5>{{ teaching.start_month }}</h5>#}
{#                            <h5>{{ teaching.start_year }}</h5>#}
{#                            <br>#}
{#                            <!-- Delete Teaching -->#}
{#                            <form action="{% url 'accounts:delete_teaching' teaching.id %}" method="post" style="display: inline;">#}
{#                                {% csrf_token %}#}
{#                                <input type="hidden" name="teaching_id" value="{{ teaching.id }}" />#}
{#                                <button type="submit" class="btn btn-default btn-sm">#}
{#                                    <span class="glyphicon glyphicon-trash"></span>#}
{#                                </button>#}
{#                            </form>#}
{##}
{#                                </div>#}
{#                            </div>#}
{#                        </div>#}
{#                    </li>#}
{#                {% endif %}#}
{#        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}#}
{#            {% endfor %}#}
{#        {% endif %}#}
{#        </ul>#}


    </div>
</div>

{% endblock %}  

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block body %}
  <div class="container">
    <div class="backbox">
      <div class="loginMsg">
        <div class="textcontent">
          <p class="title">Don't have an account?  </p>
          <p>Sign up to Continue.</p>
            <button id="switch1">Sign Up</button>
        </div>
      </div>
      <div class="signupMsg visibility">
        <div class="textcontent">
          <p class="title">Have an account?</p>
          <p>Log in to see your account.</p>
          <button id="switch2">LOG IN</button>
        </div>
      </div>
    </div>
    <!-- backbox -->

    <div class="frontbox">
      <div class="login">
        <h2>LOG IN</h2>
         <form  class = "form-horizontal" role="form" action="{% url 'accounts:login_user'%}" method = "POST" enctype="multipart/form-data">
            {% csrf_token %}
          <div class="inputbox">
             <input type="text" name="username" placeholder="  Username">
             <input type="password" name="password" placeholder="  PASSWORD">
          </div>
          {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
          {% endif %}

            <footer><a href = "{% url 'accounts:admin' %}">Admin Page</a><br> <a href="{% url 'listall' %}">List all Pages</a></footer>
                <button type="submit" class="btn btn-success">Login</button>
          </form>
      </div>
      
      


      <div class="signup hide">
        <h2>SIGN UP</h2>
        <div class="inputbox">
          
        
         <form class="form-horizontal" role="form" action="{% url 'accounts:register'%}" method="POST" enctype="multipart/form-data">
             {% csrf_token %}
             <div class="inputbox">
                <input type="text" name="username" placeholder="  Username">
                 <input type="text" name="email" placeholder="  Email">
                <input type="password" name="password" placeholder="  PASSWORD">
                 <input type="password" name="password1" placeholder="  CONFIRM PASSWORD">
             <div class="g-recaptcha" data-sitekey="6LdOmjcUAAAAAANOqIL3g99NaAwxg_2ShBFMh4MX" style="transform:scale(0.77);-webkit-transform:scale(0.55);transform-origin:0 0;-webkit-transform-origin:0 0;"></div>
{#                 {% if error_message %}#}
{#        <p><strong>{{ error_message }}</strong></p>#}
{#          {% endif %}#}
          </div>

          <button type="submit" class="btn btn-success">Submit</button>
        </form>
        </div>
      </div>

    </div>
    <!-- frontbox -->
  </div>

{% endblock %}