achievements/urls.py
from django.conf.urls import url, include
from . import views
from accounts import views as accounts_views
from homepage import views as homepage_views

app_name = 'achievements'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^$', views.index, name='to_achievements'),
    url(r'^logout/$', views.logoutss, name='logout'),
    url(r'^create_achievement/$', views.create_achievement, name='create_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/delete_achievement/$', views.delete_achievement, name='delete_achievement'),
    url(r'^(?P<ach_id>[0-99]+)/edit_achievement/$', views.edit_achievement, name='edit_achievement'),
    url(r'^to_homepage/$', homepage_views.index, name='to_homepage'),
    url(r'^ldach$', views.loaddata, name='ldach'),
    url(r'^searched_achievements/$', views.searched_achievements, name='searched_achievements'),
]

fileread/urls.py
from django.conf.urls import url ,include
from . import views
from accounts import views as accounts_views
from homepage import views as homepage_views

app_name = 'fileread'

urlpatterns = [
	url(r'^$', views.index, name='index'),
	
	]

ssl2/urls.py
from django.conf.urls import url,include
from django.conf.urls.static import static
from django.contrib import admin
from accounts import views as accounts_views
from django.conf import settings


app_name = 'accounts'

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('homepage.urls')),
    url(r'^homepage/', include('homepage.urls')),
    url(r'^achievements/', include('achievements.urls', namespace="achievements")),
    url(r'^viewonly/', include('viewonly.urls', namespace="viewonly")),
    url(r'^listall/', accounts_views.listall, name='listall'),
    url(r'^publications/', include('publications.urls', namespace="publications")),
    url(r'^infop/', include('infop.urls', namespace="infop")),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

achievements/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class Achievements(models.Model):
    user = models.ForeignKey(User, default=1)
    achievement = models.CharField(max_length=250)

    def __str__(self):
        return self.user.username

fileread/models.py
from django.contrib.auth.models import Permission, User
from django.db import models


class File(models.Model):
    user = models.ForeignKey(User, default=1)
    file = models.FileField()

achievements/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Achievements


class AchievementsForm(forms.ModelForm):

    class Meta:
        model = Achievements
        fields = ['achievement']

fileread/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import File


class FileForm(forms.ModelForm):

    class Meta:
        model = File
        fields = ['file']

achievements/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from .forms import AchievementsForm
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from .models import Achievements
from infop.models import Info
import requests
from bs4 import BeautifulSoup

def index(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        achnts = Achievements.objects.filter(user=request.user)
        bio = Info.objects.filter(user=request.user)
        return render(request, 'achievements/index.html', {'anshp': bio,'achievements': achnts})

def logoutss(request):
    logout(request)
    return render(request, 'accounts/login.html')

def create_achievement(request):
    if not request.user.is_authenticated():
        return render(request, 'accounts/login.html')
    else:
        form = AchievementsForm(request.POST or None)
        if form.is_valid():
            achievement = form.save(commit=False)
            achievement.user = request.user                                  
            achievement.save()
            achievements = Achievements.objects.filter(user=request.user)
            return render(request, 'achievements/index.html', {'achievements': achievements})
        context = {
            "form": form,
        }
        return render(request, 'achievements/add_achievement.html', context)

def delete_achievement(request, ach_id):
    tobedeleted = Achievements.objects.get(pk=ach_id)
    tobedeleted.delete()
    achievements = Achievements.objects.filter(user=request.user)
    return render(request, 'achievements/index.html', {'achievements': achievements})


def edit_achievement(request, ach_id):
    tobeedited = Achievements.objects.get(pk=ach_id)
    Achievements.objects.get(pk=ach_id).delete()
    return render(request, 'achievements/add_achievement.html', {'tobeedited': tobeedited , 'error':'aaa'})


def searched_achievements(request):
    achievements = Achievements.objects.filter(user=request.user)
    searched_achievement = request.POST['search1']
    context = {
        'achievements': achievements,
        'searched_achievement': searched_achievement,
    }
    return render(request, 'achievements/searched_achievements.html', context)

def loaddata(request):
    linkobj = Info.objects.filter(user=request.user).first()

    url = linkobj.link

    dic = {}

    res = []

    r  = requests.get(url)

    data = r.text

    # soup = BeautifulSoup(data,'lxml')
    soup = BeautifulSoup(data)

    main = soup.find("div",{ "id" : "fh5co-main" })

    content = soup.find("div",{ "data-content" : "7" })

    ul = content.find("ul")

    publications = ul.find_all("li")

    for item in publications :
        te = item.text

        publ = Achievements.objects.create()

        publ.user = request.user

        publ.achievement = te

        publ.save()

    publiions = Achievements.objects.filter(user=request.user)
    return render(request, 'achievements/index.html', {'achievements': publiions})

fileread/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import authenticate, login, logout
import json
import urllib
from django.conf import settings
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.shortcuts import render
from .models import File
from .forms import FileForm

def index(request):
	f=open("abc.txt", "r")
	contents =f.read()
	f.close()
	return render(request,'fileread/main.html',{'content': contents})
	

fileread/templates/achievements/add_achievement.html
{% extends 'base.html' %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add an Achievement</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {{ form }}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock %}

fileread/templates/achievements/index.html
{% extends 'base.html' %}

{% block body %}

<h2>Enter achievement data</h2>

<form action="{% url 'achievements:to_homepage' %}" method="post" style="display: inline;">
    {% csrf_token %}
    <input type="hidden" name="to_home_page"/>
    <button type="submit" class="btn btn-default btn-sm">
        Go to homepage
    </button>
</form>

{% if  achievements %}
            {% for ach in achievements %}
                <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <div class="caption">
                    <h2>{{ ach.achievement }} </h2>
                    <form action="{% url 'achievements:delete_achievement'  ach.id %}" method="post" style="display: inline;">
                        {% csrf_token %}
                        <input type="hidden" name="ach_id" value="{{ ach.id }}" />
                        <button type="submit" class="btn btn-default btn-sm">
                            <span class="glyphicon glyphicon-trash"></span>
                        </button>
                    </form>
                    
                        </div>
                    </div>
                </div>
        {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
{% endif %}
<div class="col-sm-12">
    <a href="{% url 'achievements:create_achievement' %}">
        <button type="button" class="btn btn-success">
            <span class="glyphicon glyphicon-plus">Add Achievement</span>
        </button>
    </a>
</div>


<form action = "{% url 'accounts:logout' %}" method = "POST">
    {% csrf_token %}
    <button type = "submit"> LOGOUT </button>
</form>

{% endblock %}